### ISSUE TITLE
example script in an early mouse embryo dataset from Chan et al

### ISSUE THREAD

**Issue by akhst7** [ZhangLabGT/LinRace#2]
HI,  Could you post a semi-detail of a script for analyzing an early mouse embryo dataset from Chan et al , stating from importing 10x data ?  

Thanks.

**Comment by Galaxeee** [comment]
Yes, you can refer to the vignette: vignettes/Mouse_test.Rmd.
For the 10x data, I have not currently uploaded the matrix.mtx.gz files due to LFS storage limits, but you can find it in the database: [GSE117542](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE117542)

**Comment by akhst7** [comment]
@Galaxeee,   Thanks.   For 10X, fastq will do.
