### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by thelingxichen** [ZhangLabGT/LinRace#3]
Dear @Galaxeee ,

I have read your NC paper and tried to install the package using `devtools::install_github("https://github.com/ZhangLabGT/LinRace")` with R version 4.2.2 and R 4.3.2. Both versions encountered the following errors:

```
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'oped organs is one o ...' is malformed!
```

Could you share the R version you use and help me with this?

Best,
Lingxi

**Comment by SuqinYang** [comment]
I met the same error, do you have an solution?

**Comment by Galaxeee** [comment]
Sorry for the late response. We have manually copied the wrong description file to cause this issue. And I have updated the description file and it should be good.
